# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

linters:
  enable:
    - depguard

issues:
  exclude-rules:
    # Allow usage of deprecated values.
    - linters: [staticcheck]
      text: "SA1019:"
      path: "(pkg/consuldp/bootstrap.go)"

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: github.com/armon/go-metrics
            desc: "use github.com/hashicorp/go-metrics"
          - pkg: github.com/hashicorp/go-metrics/compat
            desc: "use github.com/hashicorp/go-metrics"
