# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

issues:
  exclude-rules:
    # Allow usage of deprecated values.
    - linters: [ staticcheck ]
      text: 'SA1019:'
      path: "(pkg/consuldp/bootstrap.go)"