# Copyright IBM Corp. 2022, 2026

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "internal/mocks/**"
  - "pkg/**/mock_*.go"
  - "integration-tests/**"
