# DANGER: this dockerfile is experimental and could be modified/removed at any time.
# A simple image for testing changes to consul-dataplane
#
# Meant to be used with the following make target
# DEV_IMAGE=<name:tag> make skaffold

FROM hashicorp/consul-dataplane as cache
ARG TARGETARCH

COPY dist/linux/${TARGETARCH}/consul-dataplane /usr/local/bin/
