// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pbdataplane/broker.proto

package pbdataplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_pbdataplane_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_pbdataplane_broker_proto_rawDescGZIP(), []int{0}
}

func (x *GetKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetKeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyMaterial      []byte                 `protobuf:"bytes,2,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"`
	Algorithm        string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	NotBeforeUnix    int64                  `protobuf:"varint,4,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`
	RefreshAfterUnix int64                  `protobuf:"varint,5,opt,name=refresh_after_unix,json=refreshAfterUnix,proto3" json:"refresh_after_unix,omitempty"`
	ExpiresAtUnix    int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_pbdataplane_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_pbdataplane_broker_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetKeyResponse) GetKeyMaterial() []byte {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

func (x *GetKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetKeyResponse) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *GetKeyResponse) GetRefreshAfterUnix() int64 {
	if x != nil {
		return x.RefreshAfterUnix
	}
	return 0
}

func (x *GetKeyResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type GetBrokerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrokerStatusRequest) Reset() {
	*x = GetBrokerStatusRequest{}
	mi := &file_pbdataplane_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrokerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerStatusRequest) ProtoMessage() {}

func (x *GetBrokerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBrokerStatusRequest) Descriptor() ([]byte, []int) {
	return file_pbdataplane_broker_proto_rawDescGZIP(), []int{2}
}

type GetBrokerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	KeysCached    int32                  `protobuf:"varint,2,opt,name=keys_cached,json=keysCached,proto3" json:"keys_cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBrokerStatusResponse) Reset() {
	*x = GetBrokerStatusResponse{}
	mi := &file_pbdataplane_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBrokerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerStatusResponse) ProtoMessage() {}

func (x *GetBrokerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetBrokerStatusResponse) Descriptor() ([]byte, []int) {
	return file_pbdataplane_broker_proto_rawDescGZIP(), []int{3}
}

func (x *GetBrokerStatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetBrokerStatusResponse) GetKeysCached() int32 {
	if x != nil {
		return x.KeysCached
	}
	return 0
}

var File_pbdataplane_broker_proto protoreflect.FileDescriptor

const file_pbdataplane_broker_proto_rawDesc = "" +
	"\n" +
	"\x18pbdataplane/broker.proto\x12\x1ahashicorp.consul.dataplane\"&\n" +
	"\rGetKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\xe6\x01\n" +
	"\x0eGetKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12!\n" +
	"\fkey_material\x18\x02 \x01(\fR\vkeyMaterial\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12&\n" +
	"\x0fnot_before_unix\x18\x04 \x01(\x03R\rnotBeforeUnix\x12,\n" +
	"\x12refresh_after_unix\x18\x05 \x01(\x03R\x10refreshAfterUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix\"\x18\n" +
	"\x16GetBrokerStatusRequest\"P\n" +
	"\x17GetBrokerStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1f\n" +
	"\vkeys_cached\x18\x02 \x01(\x05R\n" +
	"keysCached2\xf4\x01\n" +
	"\x15LocalCredentialBroker\x12_\n" +
	"\x06GetKey\x12).hashicorp.consul.dataplane.GetKeyRequest\x1a*.hashicorp.consul.dataplane.GetKeyResponse\x12z\n" +
	"\x0fGetBrokerStatus\x122.hashicorp.consul.dataplane.GetBrokerStatusRequest\x1a3.hashicorp.consul.dataplane.GetBrokerStatusResponseB6Z4github.com/hashicorp/consul/proto-public/pbdataplaneb\x06proto3"

var (
	file_pbdataplane_broker_proto_rawDescOnce sync.Once
	file_pbdataplane_broker_proto_rawDescData []byte
)

func file_pbdataplane_broker_proto_rawDescGZIP() []byte {
	file_pbdataplane_broker_proto_rawDescOnce.Do(func() {
		file_pbdataplane_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbdataplane_broker_proto_rawDesc), len(file_pbdataplane_broker_proto_rawDesc)))
	})
	return file_pbdataplane_broker_proto_rawDescData
}

var file_pbdataplane_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pbdataplane_broker_proto_goTypes = []any{
	(*GetKeyRequest)(nil),           // 0: hashicorp.consul.dataplane.GetKeyRequest
	(*GetKeyResponse)(nil),          // 1: hashicorp.consul.dataplane.GetKeyResponse
	(*GetBrokerStatusRequest)(nil),  // 2: hashicorp.consul.dataplane.GetBrokerStatusRequest
	(*GetBrokerStatusResponse)(nil), // 3: hashicorp.consul.dataplane.GetBrokerStatusResponse
}
var file_pbdataplane_broker_proto_depIdxs = []int32{
	0, // 0: hashicorp.consul.dataplane.LocalCredentialBroker.GetKey:input_type -> hashicorp.consul.dataplane.GetKeyRequest
	2, // 1: hashicorp.consul.dataplane.LocalCredentialBroker.GetBrokerStatus:input_type -> hashicorp.consul.dataplane.GetBrokerStatusRequest
	1, // 2: hashicorp.consul.dataplane.LocalCredentialBroker.GetKey:output_type -> hashicorp.consul.dataplane.GetKeyResponse
	3, // 3: hashicorp.consul.dataplane.LocalCredentialBroker.GetBrokerStatus:output_type -> hashicorp.consul.dataplane.GetBrokerStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbdataplane_broker_proto_init() }
func file_pbdataplane_broker_proto_init() {
	if File_pbdataplane_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbdataplane_broker_proto_rawDesc), len(file_pbdataplane_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbdataplane_broker_proto_goTypes,
		DependencyIndexes: file_pbdataplane_broker_proto_depIdxs,
		MessageInfos:      file_pbdataplane_broker_proto_msgTypes,
	}.Build()
	File_pbdataplane_broker_proto = out.File
	file_pbdataplane_broker_proto_goTypes = nil
	file_pbdataplane_broker_proto_depIdxs = nil
}
