// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: pbdataplane/broker.proto

package pbdataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalCredentialBroker_GetKey_FullMethodName          = "/hashicorp.consul.dataplane.LocalCredentialBroker/GetKey"
	LocalCredentialBroker_GetBrokerStatus_FullMethodName = "/hashicorp.consul.dataplane.LocalCredentialBroker/GetBrokerStatus"
)

// LocalCredentialBrokerClient is the client API for LocalCredentialBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalCredentialBroker is the Sidecar-B UDS contract. Creating the socket is
// the authorization; the caller cannot name another service.
type LocalCredentialBrokerClient interface {
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	GetBrokerStatus(ctx context.Context, in *GetBrokerStatusRequest, opts ...grpc.CallOption) (*GetBrokerStatusResponse, error)
}

type localCredentialBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalCredentialBrokerClient(cc grpc.ClientConnInterface) LocalCredentialBrokerClient {
	return &localCredentialBrokerClient{cc}
}

func (c *localCredentialBrokerClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, LocalCredentialBroker_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localCredentialBrokerClient) GetBrokerStatus(ctx context.Context, in *GetBrokerStatusRequest, opts ...grpc.CallOption) (*GetBrokerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBrokerStatusResponse)
	err := c.cc.Invoke(ctx, LocalCredentialBroker_GetBrokerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalCredentialBrokerServer is the server API for LocalCredentialBroker service.
// All implementations should embed UnimplementedLocalCredentialBrokerServer
// for forward compatibility.
//
// LocalCredentialBroker is the Sidecar-B UDS contract. Creating the socket is
// the authorization; the caller cannot name another service.
type LocalCredentialBrokerServer interface {
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	GetBrokerStatus(context.Context, *GetBrokerStatusRequest) (*GetBrokerStatusResponse, error)
}

// UnimplementedLocalCredentialBrokerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalCredentialBrokerServer struct{}

func (UnimplementedLocalCredentialBrokerServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedLocalCredentialBrokerServer) GetBrokerStatus(context.Context, *GetBrokerStatusRequest) (*GetBrokerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrokerStatus not implemented")
}
func (UnimplementedLocalCredentialBrokerServer) testEmbeddedByValue() {}

// UnsafeLocalCredentialBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalCredentialBrokerServer will
// result in compilation errors.
type UnsafeLocalCredentialBrokerServer interface {
	mustEmbedUnimplementedLocalCredentialBrokerServer()
}

func RegisterLocalCredentialBrokerServer(s grpc.ServiceRegistrar, srv LocalCredentialBrokerServer) {
	// If the following call pancis, it indicates UnimplementedLocalCredentialBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalCredentialBroker_ServiceDesc, srv)
}

func _LocalCredentialBroker_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalCredentialBrokerServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalCredentialBroker_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalCredentialBrokerServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalCredentialBroker_GetBrokerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrokerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalCredentialBrokerServer).GetBrokerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalCredentialBroker_GetBrokerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalCredentialBrokerServer).GetBrokerStatus(ctx, req.(*GetBrokerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalCredentialBroker_ServiceDesc is the grpc.ServiceDesc for LocalCredentialBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalCredentialBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.consul.dataplane.LocalCredentialBroker",
	HandlerType: (*LocalCredentialBrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _LocalCredentialBroker_GetKey_Handler,
		},
		{
			MethodName: "GetBrokerStatus",
			Handler:    _LocalCredentialBroker_GetBrokerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbdataplane/broker.proto",
}
