// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: pbdataplane/workload_key.proto

package pbdataplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchKeyRequest identifies a content-encryption key. Authorization is the
// authenticated dataplane session (ACL token + proxy identity), not a
// caller-supplied workload_id.
type FetchKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ProxyId       string                 `protobuf:"bytes,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Partition     string                 `protobuf:"bytes,6,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchKeyRequest) Reset() {
	*x = FetchKeyRequest{}
	mi := &file_pbdataplane_workload_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchKeyRequest) ProtoMessage() {}

func (x *FetchKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_workload_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchKeyRequest.ProtoReflect.Descriptor instead.
func (*FetchKeyRequest) Descriptor() ([]byte, []int) {
	return file_pbdataplane_workload_key_proto_rawDescGZIP(), []int{0}
}

func (x *FetchKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *FetchKeyRequest) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *FetchKeyRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FetchKeyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FetchKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FetchKeyRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type FetchKeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeyId            string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	KeyMaterial      []byte                 `protobuf:"bytes,2,opt,name=key_material,json=keyMaterial,proto3" json:"key_material,omitempty"`
	Algorithm        string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	NotBeforeUnix    int64                  `protobuf:"varint,4,opt,name=not_before_unix,json=notBeforeUnix,proto3" json:"not_before_unix,omitempty"`
	RefreshAfterUnix int64                  `protobuf:"varint,5,opt,name=refresh_after_unix,json=refreshAfterUnix,proto3" json:"refresh_after_unix,omitempty"`
	ExpiresAtUnix    int64                  `protobuf:"varint,6,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchKeyResponse) Reset() {
	*x = FetchKeyResponse{}
	mi := &file_pbdataplane_workload_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchKeyResponse) ProtoMessage() {}

func (x *FetchKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pbdataplane_workload_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchKeyResponse.ProtoReflect.Descriptor instead.
func (*FetchKeyResponse) Descriptor() ([]byte, []int) {
	return file_pbdataplane_workload_key_proto_rawDescGZIP(), []int{1}
}

func (x *FetchKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *FetchKeyResponse) GetKeyMaterial() []byte {
	if x != nil {
		return x.KeyMaterial
	}
	return nil
}

func (x *FetchKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *FetchKeyResponse) GetNotBeforeUnix() int64 {
	if x != nil {
		return x.NotBeforeUnix
	}
	return 0
}

func (x *FetchKeyResponse) GetRefreshAfterUnix() int64 {
	if x != nil {
		return x.RefreshAfterUnix
	}
	return 0
}

func (x *FetchKeyResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_pbdataplane_workload_key_proto protoreflect.FileDescriptor

const file_pbdataplane_workload_key_proto_rawDesc = "" +
	"\n" +
	"\x1epbdataplane/workload_key.proto\x12\x1ahashicorp.consul.dataplane\"\xb5\x01\n" +
	"\x0fFetchKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x19\n" +
	"\bproxy_id\x18\x02 \x01(\tR\aproxyId\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tpartition\x18\x06 \x01(\tR\tpartition\"\xe8\x01\n" +
	"\x10FetchKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12!\n" +
	"\fkey_material\x18\x02 \x01(\fR\vkeyMaterial\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12&\n" +
	"\x0fnot_before_unix\x18\x04 \x01(\x03R\rnotBeforeUnix\x12,\n" +
	"\x12refresh_after_unix\x18\x05 \x01(\x03R\x10refreshAfterUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\x06 \x01(\x03R\rexpiresAtUnix2{\n" +
	"\x12WorkloadKeyService\x12e\n" +
	"\bFetchKey\x12+.hashicorp.consul.dataplane.FetchKeyRequest\x1a,.hashicorp.consul.dataplane.FetchKeyResponseB6Z4github.com/hashicorp/consul/proto-public/pbdataplaneb\x06proto3"

var (
	file_pbdataplane_workload_key_proto_rawDescOnce sync.Once
	file_pbdataplane_workload_key_proto_rawDescData []byte
)

func file_pbdataplane_workload_key_proto_rawDescGZIP() []byte {
	file_pbdataplane_workload_key_proto_rawDescOnce.Do(func() {
		file_pbdataplane_workload_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbdataplane_workload_key_proto_rawDesc), len(file_pbdataplane_workload_key_proto_rawDesc)))
	})
	return file_pbdataplane_workload_key_proto_rawDescData
}

var file_pbdataplane_workload_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbdataplane_workload_key_proto_goTypes = []any{
	(*FetchKeyRequest)(nil),  // 0: hashicorp.consul.dataplane.FetchKeyRequest
	(*FetchKeyResponse)(nil), // 1: hashicorp.consul.dataplane.FetchKeyResponse
}
var file_pbdataplane_workload_key_proto_depIdxs = []int32{
	0, // 0: hashicorp.consul.dataplane.WorkloadKeyService.FetchKey:input_type -> hashicorp.consul.dataplane.FetchKeyRequest
	1, // 1: hashicorp.consul.dataplane.WorkloadKeyService.FetchKey:output_type -> hashicorp.consul.dataplane.FetchKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbdataplane_workload_key_proto_init() }
func file_pbdataplane_workload_key_proto_init() {
	if File_pbdataplane_workload_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbdataplane_workload_key_proto_rawDesc), len(file_pbdataplane_workload_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pbdataplane_workload_key_proto_goTypes,
		DependencyIndexes: file_pbdataplane_workload_key_proto_depIdxs,
		MessageInfos:      file_pbdataplane_workload_key_proto_msgTypes,
	}.Build()
	File_pbdataplane_workload_key_proto = out.File
	file_pbdataplane_workload_key_proto_goTypes = nil
	file_pbdataplane_workload_key_proto_depIdxs = nil
}
