// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.5
// source: pbdataplane/workload_key.proto

package pbdataplane

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadKeyService_FetchKey_FullMethodName = "/hashicorp.consul.dataplane.WorkloadKeyService/FetchKey"
)

// WorkloadKeyServiceClient is the client API for WorkloadKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadKeyServiceClient interface {
	FetchKey(ctx context.Context, in *FetchKeyRequest, opts ...grpc.CallOption) (*FetchKeyResponse, error)
}

type workloadKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadKeyServiceClient(cc grpc.ClientConnInterface) WorkloadKeyServiceClient {
	return &workloadKeyServiceClient{cc}
}

func (c *workloadKeyServiceClient) FetchKey(ctx context.Context, in *FetchKeyRequest, opts ...grpc.CallOption) (*FetchKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchKeyResponse)
	err := c.cc.Invoke(ctx, WorkloadKeyService_FetchKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadKeyServiceServer is the server API for WorkloadKeyService service.
// All implementations should embed UnimplementedWorkloadKeyServiceServer
// for forward compatibility.
type WorkloadKeyServiceServer interface {
	FetchKey(context.Context, *FetchKeyRequest) (*FetchKeyResponse, error)
}

// UnimplementedWorkloadKeyServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadKeyServiceServer struct{}

func (UnimplementedWorkloadKeyServiceServer) FetchKey(context.Context, *FetchKeyRequest) (*FetchKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchKey not implemented")
}
func (UnimplementedWorkloadKeyServiceServer) testEmbeddedByValue() {}

// UnsafeWorkloadKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadKeyServiceServer will
// result in compilation errors.
type UnsafeWorkloadKeyServiceServer interface {
	mustEmbedUnimplementedWorkloadKeyServiceServer()
}

func RegisterWorkloadKeyServiceServer(s grpc.ServiceRegistrar, srv WorkloadKeyServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkloadKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadKeyService_ServiceDesc, srv)
}

func _WorkloadKeyService_FetchKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadKeyServiceServer).FetchKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadKeyService_FetchKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadKeyServiceServer).FetchKey(ctx, req.(*FetchKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadKeyService_ServiceDesc is the grpc.ServiceDesc for WorkloadKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashicorp.consul.dataplane.WorkloadKeyService",
	HandlerType: (*WorkloadKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchKey",
			Handler:    _WorkloadKeyService_FetchKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbdataplane/workload_key.proto",
}
