# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

with-expecter: true
recursive: true
include-regex: ".*"
dir: "mocks/"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
packages:
  github.com/hashicorp/consul/proto-public/pbdns:
