// Code generated by mockery v2.41.0. DO NOT EDIT.

package pbresourcemock

import mock "github.com/stretchr/testify/mock"

// isWatchEvent_Event is an autogenerated mock type for the isWatchEvent_Event type
type isWatchEvent_Event struct {
	mock.Mock
}

// isWatchEvent_Event provides a mock function with given fields:
func (_m *isWatchEvent_Event) isWatchEvent_Event() {
	_m.Called()
}

// newIsWatchEvent_Event creates a new instance of isWatchEvent_Event. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsWatchEvent_Event(t interface {
	mock.TestingT
	Cleanup(func())
}) *isWatchEvent_Event {
	mock := &isWatchEvent_Event{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
