#!/usr/bin/env bash
# Copyright IBM Corp. 2022, 2026
# SPDX-License-Identifier: MPL-2.0
#
# Cuts a consul-dataplane point release branch, prepares it, and opens a
# release-preparation PR.
#
# Workflow:
#   1. Create   <DP_RELEASE_BRANCH>          (e.g. release/1.5.0) from a long-lived
#              source branch                 (e.g. release/1.5.x)
#   2. Create   prepare-release-<version>    from <DP_RELEASE_BRANCH>
#   3. Run      `make prepare-release`        to bump pkg/version/version.go and
#              prepend the CHANGELOG.md entry generated by `make changelog`
#   4. Open a PR: prepare-release-<version> -> <DP_RELEASE_BRANCH> and print its URL
#
# Usage:
#   export DP_RELEASE_VERSION=1.5.0        # version being released
#   export DP_PRODUCT_VERSION=1.5.0        # version shown in the CHANGELOG header
#   export DP_RELEASE_BRANCH=release/1.5.0 # point release branch (PR base)
#   export DP_LAST_RELEASE_GIT_TAG=v1.4.2  # previous release tag (changelog range)
#   ./release-scripts/prepare-release-branch.sh [options]
#
# Options:
#   -n, --dry-run   Print the commands that would run; create/change/push nothing.
#   -y, --yes       Non-interactive: skip the prompts and confirmation, use env values.
#   -h, --help      Show this help and exit.
#
# Without -y, the script prompts for every setting below, showing the current env
# value (or a derived default) that you can accept (press Enter) or override:
#   DP_RELEASE_VERSION, DP_PRODUCT_VERSION, DP_RELEASE_BRANCH, DP_SOURCE_BRANCH,
#   DP_LAST_RELEASE_GIT_TAG, DP_RELEASE_DATE, REMOTE
#
# Derived defaults (used when the corresponding env var is unset):
#   DP_PRODUCT_VERSION = DP_RELEASE_VERSION
#   DP_RELEASE_BRANCH  = release/<DP_RELEASE_VERSION>
#   DP_SOURCE_BRANCH   = release/<major>.<minor>.x
#   DP_RELEASE_DATE    = today (e.g. "July 1, 2026")
#   REMOTE             = origin

set -euo pipefail

usage() {
  sed -n '/^# Cuts /,/^set /p' "$0" | sed '/^set /d; s/^# \{0,1\}//; s/^#$//'
}

# -----------------------------------------------------------------------------
# Flags
# -----------------------------------------------------------------------------
DRY_RUN=false
INTERACTIVE=true
for arg in "$@"; do
  case "${arg}" in
    -n | --dry-run) DRY_RUN=true ;;
    -y | --yes) INTERACTIVE=false ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: ${arg}" >&2
      usage >&2
      exit 1
      ;;
  esac
done

# run CMD...  Runs CMD, or in dry-run mode prints it (shell-quoted) instead.
run() {
  if [[ "${DRY_RUN}" == "true" ]]; then
    { printf '  [dry-run] $'; printf ' %q' "$@"; printf '\n'; }
  else
    "$@"
  fi
}

# fail_or_warn MESSAGE  Errors out normally; in dry-run only warns so the preview
# can run to completion.
fail_or_warn() {
  if [[ "${DRY_RUN}" == "true" ]]; then
    echo "Warning (dry-run): $1" >&2
  else
    echo "Error: $1" >&2
    exit 1
  fi
}

# prompt_var VAR_NAME DEFAULT_VALUE [required]
# Shows the value that will be used and lets the user accept or override it.
prompt_var() {
  local var_name="$1"
  local default_value="$2"
  local required="${3:-}"
  local input
  while :; do
    read -r -p "  ${var_name} [${default_value}]: " input || true
    input="${input:-${default_value}}"
    if [[ -z "${input}" && "${required}" == "required" ]]; then
      echo "  ${var_name} is required; please enter a value." >&2
      continue
    fi
    break
  done
  printf -v "${var_name}" '%s' "${input}"
}

REMOTE="${REMOTE:-origin}"

# -----------------------------------------------------------------------------
# Prerequisite checks (git is always required; the rest only warn in dry-run)
# -----------------------------------------------------------------------------
for cmd in git make gh go; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    if [[ "${cmd}" == "git" ]]; then
      echo "Error: required command 'git' not found in PATH." >&2
      exit 1
    fi
    fail_or_warn "required command '${cmd}' not found in PATH."
  fi
done

if ! gh auth status >/dev/null 2>&1; then
  fail_or_warn "GitHub CLI is not authenticated. Run 'gh auth login' and try again."
fi

# -----------------------------------------------------------------------------
# Collect / confirm settings (prompt for each, seeded from env or a default)
# -----------------------------------------------------------------------------
if [[ "${INTERACTIVE}" == "true" ]]; then
  echo "Confirm release settings (press Enter to keep the shown value, or type a new one):"
  echo
fi

# DP_RELEASE_VERSION comes first because the other defaults derive from it.
DP_RELEASE_VERSION="${DP_RELEASE_VERSION:-}"
if [[ "${INTERACTIVE}" == "true" ]]; then
  prompt_var DP_RELEASE_VERSION "${DP_RELEASE_VERSION}" required
fi
: "${DP_RELEASE_VERSION:?DP_RELEASE_VERSION is required (set it or run interactively)}"

# Derive defaults from the (possibly just-entered) version.
_major="${DP_RELEASE_VERSION%%.*}"
_rest="${DP_RELEASE_VERSION#*.}"
_minor="${_rest%%.*}"
DP_PRODUCT_VERSION="${DP_PRODUCT_VERSION:-${DP_RELEASE_VERSION}}"
DP_RELEASE_BRANCH="${DP_RELEASE_BRANCH:-release/${DP_RELEASE_VERSION}}"
DP_SOURCE_BRANCH="${DP_SOURCE_BRANCH:-release/${_major}.${_minor}.x}"
DP_RELEASE_DATE="${DP_RELEASE_DATE:-$(date "+%B %-d, %Y")}"
DP_LAST_RELEASE_GIT_TAG="${DP_LAST_RELEASE_GIT_TAG:-}"

if [[ "${INTERACTIVE}" == "true" ]]; then
  prompt_var DP_PRODUCT_VERSION      "${DP_PRODUCT_VERSION}"      required
  prompt_var DP_RELEASE_BRANCH       "${DP_RELEASE_BRANCH}"       required
  prompt_var DP_SOURCE_BRANCH        "${DP_SOURCE_BRANCH}"        required
  prompt_var DP_LAST_RELEASE_GIT_TAG "${DP_LAST_RELEASE_GIT_TAG}" required
  prompt_var DP_RELEASE_DATE         "${DP_RELEASE_DATE}"         required
  prompt_var REMOTE                  "${REMOTE}"                  required
  echo
fi
: "${DP_LAST_RELEASE_GIT_TAG:?DP_LAST_RELEASE_GIT_TAG is required (set it or run interactively)}"

# Export so both `make prepare-release` and `make changelog` can read them.
export DP_RELEASE_VERSION DP_PRODUCT_VERSION DP_RELEASE_BRANCH DP_SOURCE_BRANCH \
  DP_LAST_RELEASE_GIT_TAG DP_RELEASE_DATE REMOTE

PREPARE_BRANCH="prepare-release-${DP_RELEASE_VERSION}"

# Operate from the repository root so `make` runs against the right tree.
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

# A dirty tree would be carried onto the new branches, so require a clean start.
if [[ -n "$(git status --porcelain)" ]]; then
  fail_or_warn "working tree is not clean. Commit or stash your changes first."
fi

# -----------------------------------------------------------------------------
# Show the plan (and confirm before any push / PR, which are not reversible)
# -----------------------------------------------------------------------------
cat <<EOF
The following actions will be performed on remote '${REMOTE}':

  Source branch (long-lived)           = ${DP_SOURCE_BRANCH}
  Release branch (created/used)        = ${DP_RELEASE_BRANCH}
  Prepare branch (new)                 = ${PREPARE_BRANCH}

  DP_RELEASE_VERSION                   = ${DP_RELEASE_VERSION}
  DP_PRODUCT_VERSION                   = ${DP_PRODUCT_VERSION}
  DP_LAST_RELEASE_GIT_TAG              = ${DP_LAST_RELEASE_GIT_TAG}
  CHANGELOG date                       = ${DP_RELEASE_DATE}

Steps:
  1. Create ${DP_RELEASE_BRANCH} from ${REMOTE}/${DP_SOURCE_BRANCH} (and push if new)
  2. Create ${PREPARE_BRANCH} from ${DP_RELEASE_BRANCH}
  3. Bump the version and prepend the CHANGELOG entry, then commit
  4. Push ${PREPARE_BRANCH} and open a PR into ${DP_RELEASE_BRANCH}

EOF

if [[ "${DRY_RUN}" == "true" ]]; then
  echo ">>> DRY RUN: nothing will be created, changed, pushed, or opened."
  echo ">>> The commands that would run are printed below, prefixed with [dry-run]."
  echo ">>> Branch-existence checks use your local clone; run 'git fetch ${REMOTE}' first for accuracy."
  echo
elif [[ "${INTERACTIVE}" == "true" ]]; then
  read -r -p "Proceed? [y/N] " response || true
  case "${response}" in
    [yY] | [yY][eE][sS]) ;;
    *)
      echo "Aborted. No changes were made."
      exit 1
      ;;
  esac
fi

# -----------------------------------------------------------------------------
# 1. Create (or reuse) the point release branch from the long-lived source branch
# -----------------------------------------------------------------------------
echo "==> Fetching latest from ${REMOTE}..."
run git fetch "${REMOTE}"

if git show-ref --verify --quiet "refs/heads/${PREPARE_BRANCH}"; then
  fail_or_warn "local branch '${PREPARE_BRANCH}' already exists. Delete it or pick another version."
fi
if git rev-parse --verify --quiet "refs/remotes/${REMOTE}/${PREPARE_BRANCH}" >/dev/null; then
  fail_or_warn "branch '${PREPARE_BRANCH}' already exists on ${REMOTE}. Delete it or pick another version."
fi

if git rev-parse --verify --quiet "refs/remotes/${REMOTE}/${DP_RELEASE_BRANCH}" >/dev/null; then
  echo "==> ${DP_RELEASE_BRANCH} already exists on ${REMOTE}; using it as-is."
  run git checkout -B "${DP_RELEASE_BRANCH}" "${REMOTE}/${DP_RELEASE_BRANCH}"
else
  if ! git rev-parse --verify --quiet "refs/remotes/${REMOTE}/${DP_SOURCE_BRANCH}" >/dev/null; then
    fail_or_warn "source branch '${DP_SOURCE_BRANCH}' not found on ${REMOTE}. Set DP_SOURCE_BRANCH to the long-lived branch to cut from."
  fi
  echo "==> Creating ${DP_RELEASE_BRANCH} from ${REMOTE}/${DP_SOURCE_BRANCH}..."
  run git checkout -b "${DP_RELEASE_BRANCH}" "${REMOTE}/${DP_SOURCE_BRANCH}"
  run git push -u "${REMOTE}" "${DP_RELEASE_BRANCH}"
fi

# -----------------------------------------------------------------------------
# 2. Create the prepare branch from the point release branch
# -----------------------------------------------------------------------------
echo "==> Creating ${PREPARE_BRANCH} from ${DP_RELEASE_BRANCH}..."
run git checkout -b "${PREPARE_BRANCH}"

# -----------------------------------------------------------------------------
# 3. Prepare the release: bump the version and prepend the CHANGELOG entry
# -----------------------------------------------------------------------------
echo "==> Bumping pkg/version/version.go to ${DP_RELEASE_VERSION} ('make prepare-release')..."
run make prepare-release DP_RELEASE_VERSION="${DP_RELEASE_VERSION}"

echo "==> Generating CHANGELOG entry since ${DP_LAST_RELEASE_GIT_TAG} ('make changelog')..."
if [[ "${DRY_RUN}" == "true" ]]; then
  printf '  [dry-run] $ make -s changelog DP_LAST_RELEASE_GIT_TAG=%q\n' "${DP_LAST_RELEASE_GIT_TAG}"
  printf "  [dry-run] prepend '## %s (%s)' + the changelog body to CHANGELOG.md\n" \
    "${DP_PRODUCT_VERSION}" "${DP_RELEASE_DATE}"
else
  # `make changelog` writes the changelog body (SECURITY/IMPROVEMENTS/... sections)
  # to stdout; -s keeps make from echoing the recipe so we capture a clean body.
  changelog_body="$(make -s changelog DP_LAST_RELEASE_GIT_TAG="${DP_LAST_RELEASE_GIT_TAG}")"
  # Drop the leading blank line(s) emitted by the changelog template.
  changelog_body="$(printf '%s\n' "${changelog_body}" | awk 'NF{f=1} f')"

  if [[ -z "${changelog_body}" ]]; then
    echo "Error: 'make changelog' produced no entries between ${DP_LAST_RELEASE_GIT_TAG} and HEAD." >&2
    exit 1
  fi

  echo "==> Prepending '## ${DP_PRODUCT_VERSION} (${DP_RELEASE_DATE})' to CHANGELOG.md..."
  {
    printf '## %s (%s)\n' "${DP_PRODUCT_VERSION}" "${DP_RELEASE_DATE}"
    printf '%s\n\n' "${changelog_body}"
    cat CHANGELOG.md
  } >CHANGELOG.md.new
  mv CHANGELOG.md.new CHANGELOG.md
fi

if [[ "${DRY_RUN}" != "true" && -z "$(git status --porcelain)" ]]; then
  echo "Error: release preparation produced no changes; nothing to commit." >&2
  exit 1
fi

run git add -A
run git commit -m "changelog and version update ${DP_RELEASE_VERSION}"

# -----------------------------------------------------------------------------
# 4. Push the prepare branch and open the PR
# -----------------------------------------------------------------------------
echo "==> Pushing ${PREPARE_BRANCH} to ${REMOTE}..."
run git push -u "${REMOTE}" "${PREPARE_BRANCH}"

PR_TITLE="Prepare release ${DP_RELEASE_VERSION}"
PR_BODY="$(cat <<EOF
Automated release preparation for consul-dataplane ${DP_RELEASE_VERSION}.

Generated by \`release-scripts/prepare-release-branch.sh\`:
- Bumped \`pkg/version/version.go\` to ${DP_RELEASE_VERSION} (\`make prepare-release\`).
- Prepended the ${DP_PRODUCT_VERSION} CHANGELOG entry (\`make changelog\`, since ${DP_LAST_RELEASE_GIT_TAG}).

Base branch \`${DP_RELEASE_BRANCH}\` was cut from \`${DP_SOURCE_BRANCH}\`.
EOF
)"

echo "==> Opening pull request: ${PREPARE_BRANCH} -> ${DP_RELEASE_BRANCH}..."
if [[ "${DRY_RUN}" == "true" ]]; then
  printf '  [dry-run] $ gh pr create --base %q --head %q --title %q --body <PR body>\n' \
    "${DP_RELEASE_BRANCH}" "${PREPARE_BRANCH}" "${PR_TITLE}"
  echo
  echo "Dry run complete. No branches were created and nothing was pushed."
  exit 0
fi

PR_URL="$(gh pr create \
  --base "${DP_RELEASE_BRANCH}" \
  --head "${PREPARE_BRANCH}" \
  --title "${PR_TITLE}" \
  --body "${PR_BODY}")"

echo
echo "Pull request created:"
echo "${PR_URL}"
