// Code generated by mockery v2.32.0. DO NOT EDIT.

package pbdnsmock

import (
	context "context"

	pbdns "github.com/hashicorp/consul/proto-public/pbdns"
	mock "github.com/stretchr/testify/mock"
)

// DNSServiceServer is an autogenerated mock type for the DNSServiceServer type
type DNSServiceServer struct {
	mock.Mock
}

// Query provides a mock function with given fields: _a0, _a1
func (_m *DNSServiceServer) Query(_a0 context.Context, _a1 *pbdns.QueryRequest) (*pbdns.QueryResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pbdns.QueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbdns.QueryRequest) (*pbdns.QueryResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbdns.QueryRequest) *pbdns.QueryResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbdns.QueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbdns.QueryRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDNSServiceServer creates a new instance of DNSServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDNSServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DNSServiceServer {
	mock := &DNSServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
