// Code generated by mockery v2.32.0. DO NOT EDIT.

package pbdnsmock

import mock "github.com/stretchr/testify/mock"

// IsCloningDNSServiceClient is an autogenerated mock type for the IsCloningDNSServiceClient type
type IsCloningDNSServiceClient struct {
	mock.Mock
}

// IsCloningDNSServiceClient provides a mock function with given fields:
func (_m *IsCloningDNSServiceClient) IsCloningDNSServiceClient() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewIsCloningDNSServiceClient creates a new instance of IsCloningDNSServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIsCloningDNSServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IsCloningDNSServiceClient {
	mock := &IsCloningDNSServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
