// Code generated by mockery v2.32.0. DO NOT EDIT.

package pbdnsmock

import mock "github.com/stretchr/testify/mock"

// UnsafeDNSServiceServer is an autogenerated mock type for the UnsafeDNSServiceServer type
type UnsafeDNSServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDNSServiceServer provides a mock function with given fields:
func (_m *UnsafeDNSServiceServer) mustEmbedUnimplementedDNSServiceServer() {
	_m.Called()
}

// NewUnsafeDNSServiceServer creates a new instance of UnsafeDNSServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeDNSServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeDNSServiceServer {
	mock := &UnsafeDNSServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
