#!/bin/bash

# This script pretends to be Envoy in unit tests. It captures the flags and the
# bootstrap config from the named pipe specified via `--config-path`, and writes
# them to the file at `--test-output` (which is read and checked in the test).
# It then sleeps for 10 minutes to check we're correctly killing the process.

set -e

config_path=""
test_output=""

prev_arg=""
for arg in "$@"; do
  case "$prev_arg" in
    --config-path)
      config_path="$arg"
      ;;
    --test-output)
      test_output="$arg"
      ;;
  esac
  prev_arg="$arg"
done

if [ -z "$config_path" ]; then
  >&2 echo "--config-path is required"
  exit 1
fi

if [ -z "$test_output" ]; then
  >&2 echo "--test-output is required"
  exit 1
fi

# Base64 encode the data to avoid having to escape it in the JSON output.
config_data=$(base64 -i $config_path)

cat <<EOF > "$test_output"
{
  "Args": "$@",
  "ConfigData": "$config_data"
}
EOF

sleep 600
