#!/bin/bash

# This script pretends to be Envoy in unit tests. It captures the flags and the
# bootstrap config specified via `--config-yaml`, and writes them to the file at
# `--test-output` (which is read and checked in the test).
# It then sleeps for 10 minutes to check we're correctly killing the process.

set -e

config_yaml=""
test_output=""

prev_arg=""
for arg in "$@"; do
  case "$prev_arg" in
    --config-yaml)
      config_yaml="$arg"
      ;;
    --test-output)
      test_output="$arg"
      ;;
  esac
  prev_arg="$arg"
done

if [ -z "$config_yaml" ]; then
  >&2 echo "--config-yaml is required"
  exit 1
fi

if [ -z "$test_output" ]; then
  >&2 echo "--test-output is required"
  exit 1
fi

# Base64 encode the data to avoid having to escape it in the JSON output.
args=$(echo "$@" | base64 | tr -d \\n)
config_data=$(echo -n "$config_yaml" | base64 | tr -d \\n)

cat <<EOF > "$test_output"
{
  "Args": "$args",
  "ConfigData": "$config_data"
}
EOF

sleep 600
