name: conditional-skip

on:
  workflow_call:
    outputs:
      skip-ci:
        description: "Whether we should skip build and test jobs"
        value: ${{ jobs.check-skip.outputs.skip-ci }}

jobs:
  check-skip:
    runs-on: ubuntu-latest
    name: Check whether to skip build and tests
    outputs:
      skip-ci: ${{ steps.check-changed-files.outputs.skip-ci }}
    env:
      # Use the base branch for PR, or the head of the current branch for push.
      SKIP_CHECK_BRANCH: ${{ github.base_ref || github.ref_name }}
    steps:
      - name: Ensure conditional check is allowed
        if: ${{ !github.base_ref && !github.ref_protected }}
        run: |
          echo "Conditional skip requires a PR event with 'base_ref' or 'push' to a protected branch."
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.ref_protected: ${{ github.ref_protected }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "Check the triggers of the calling workflow to ensure that these requirements are met."
          exit 1
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - name: Check changed files
        id: check-changed-files
        run: ./.github/scripts/check_skip_ci.sh